### ISSUE TITLE
pasting with `p` pastes one char ahead of selection

### ISSUE THREAD

**Issue by LucasTavaresA** [tenxsoydev/karen-yank.nvim#17]
is this expected behavior? it does not happen when pasting with `yp` which i assume does the same but yanks the text

problem: `"selected-text"` becomes `""pasted-text`
expectation:  `"selected-text"` becomes `"pasted-text"`

**Comment by tobealive** [comment]
Hey @LucasTavaresA. Thanks for reporting and giving a description of the problem. 

This is indeed a misbehavior. It should behave as it usually does in Vim, namely by replacing the text inside the brackets.

I'm tackling this tomorrow at the latest.

**Comment by tobealive** [comment]
The approach to fix this was a bit too simple, so it is not completely fixed yet. Depending on the context, the placement of the pasted text now might be one character before the selection. E.g. when inserting over a selection that goes to the end of the line.

**Comment by tobealive** [comment]
We should be good. Please let me know if it works for you too.

**Comment by LucasTavaresA** [comment]
its working fine since the revert

**Comment by tobealive** [comment]
Yep, the specific problem case the issue is mentioning was fixed. 

But when pasting over a selection, the insertion was misplaced again depending on the context. But instead of one char ahead it was one char before the initial selection.

**Comment by LucasTavaresA** [comment]
yeah it looks like still happening with the latest commit, when the selection ends at the end of a line

**Comment by tobealive** [comment]
Okay, I'll need to further investigate.

Maybe there is a difference with unix and dos line endings.

Currently, I cannot reproduce it anymore  on my end since the last change.

**Comment by LucasTavaresA** [comment]
it also depends where the selection started

assume `selected` is at the very end of the line

example:   `"" selected` becomes `""pasted` essentially removing the space
but if your selection goes right to left `"" selected` becomes `"pasted"`

**Comment by tobealive** [comment]
Thanks for helping to dig into this.

Unfortunately, I'm still not able to reproduce. Before adding the expression it was clearly the case. 

To be sure that I follow your reproduction right. Would it be possible for you to post a gif or video of the issue?

**Comment by LucasTavaresA** [comment]
i dont think it adds to much but watch this https://asciinema.org/a/KbFV0A9jfiIq5Jg2WEsLkpiEc

might be a problem on my end? or possibly some unix thing as you said

**Comment by tobealive** [comment]
Thanks m8. Got the reproduction now. But strangely it only happens on the first paste. Undo, and try to paste over it again it behaves correctly. Without the last commit I can reproduce this 100% of the time.

**Comment by LucasTavaresA** [comment]
undo is not changing anything on my side, but if you select then press `o` you can see the left/right pasting diference

**Comment by tobealive** [comment]
Yep, now I get what I'm doing wrong.

I misinterpreted the 
> it also depends where the selection started"

apologies. Yeah, the issue will be with using getcursor. As it won't get the end of the selection but the current cursor positon.

**Comment by tobealive** [comment]
Let me know if the `fix-paste` branch works for you then I'll do a little refinement and merge it.

**Comment by LucasTavaresA** [comment]
the case where it goes `"pasted"` is gone as you are not using the cursor position

the space removal was caused by https://github.com/lewis6991/spaceless.nvim, not sure how to deal with this

**Comment by tobealive** [comment]
Okay, had a moment and it wasn't that much to do. Please let me know how it works for you now @LucasTavaresA.

**Comment by LucasTavaresA** [comment]
oh that is great, its working fine
